<?php

namespace App\Service;

use App\Model\Friend;
use App\Model\Interfaces\FriendInterface;
use Core\Lib\Singleton;

class FriendService extends Singleton implements FriendInterface
{
    /**
     * @return FriendService
     */
    public static function getInstance()
    {
        return parent::getInstance(); // TODO: Change the autogenerated stub
    }

    public function getIdListByUserId(int $userId) : array
    {
        $result = Friend::getInstance()->getIdListByUserId($userId);
        $result = strlen($result) ? explode(',', $result) : [];

        return $result;
    }
}